
@startuml
actor User
participant "TicTacToe" as TicTacToe
participant "Game" as Game
participant "Home" as Home

User -> TicTacToe : render()
TicTacToe -> Home : setGameMode()
Home -> TicTacToe : Game Mode Selected
TicTacToe -> Game : render(mode, difficulty)
User -> Game : Play Game
User -> TicTacToe : Back to Home
TicTacToe -> TicTacToe : handleBackToHome()
TicTacToe -> TicTacToe : setGameMode(null)
TicTacToe -> User : render()
TicTacToe -> Home : setGameMode()
@enduml
