name: CI

on: [push, pull_request]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  sonarcloud:
    needs: [test, build]
    uses: ./.github/workflows/sonarcloud.yml

  deploy:
    needs: [build, sonarcloud]
    uses: ./.github/workflows/deploy.yml