name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm test
    - run: npm run build

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.4
      with:
        args: >
          -Dsonar.projectKey=your_project_key
          -Dsonar.organization=your_organization
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: [build, sonarcloud]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
    - run: vercel --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}